site_name: SQLAlchemy Filterset
site_description: An easy way to filter SQLAlchemy queries
repo_name: sqlalchemy-filterset
site_url: https://sqlalchemy-filterset.github.io/sqlalchemy-filterset/
repo_url: https://github.com/sqlalchemy-filterset/sqlalchemy-filterset
edit_uri: ""

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'deep purple'
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: 'deep purple'
      accent: 'deep purple'
      toggle:
          icon: material/weather-night
          name: Switch to light mode
  icon:
    logo: material/filter
    repo: fontawesome/brands/github
  favicon: img/favicon.png
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.annotate
  language: en

plugins:
  - search

nav:
  - Overview: index.md
  - Filtersets: filtersets.md
  - Filters: filters.md
  - Examples:
    - FastApi: examples/fastapi.md
  - Contributing: contributing.md

# Extensions / Plugins
markdown_extensions:
  - toc:
      permalink: true # inserts an anchor
  - admonition # notes make pretty
  - pymdownx.highlight  # better code, instead of CodeHilite
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.superfences: # nest code blocks under other blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # auto tabs
      alternate_style: true
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.snippets # insert other markdown or HTML
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - attr_list  # adds a syntax to define attributes on the various HTML elements
  - def_list  # create definition lists

extra:
  analytics:
    provider: google
    property: G-95YP40ZTZ1
